AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  anti-social-media-backend

  Sample SAM Template for anti-social-media-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  QitClickTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: qit-db-local
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createDateTime
          AttributeType: S
        - AttributeName: dateKey
          AttributeType: S
        - AttributeName: recordSort
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: createDateTime
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: dateKey
              KeyType: HASH
            - AttributeName: recordSort
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  QitUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: qit-user-local
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createDateTime
          AttributeType: S
        - AttributeName: googleId
          AttributeType: S
        - AttributeName: appleId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: createDateTime
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GoogleIdIndex
          KeySchema:
            - AttributeName: googleId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: AppleIdIndex
          KeySchema:
            - AttributeName: appleId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: qit-db-local
          DYNAMODB_ENDPOINT: http://qit-ddb-local:8000
          AWS_REGION: us-east-1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QitClickTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      ImageConfig:
        Command:
          - app.lambdaHandler
    Metadata:
      DockerTag: nodejs22.x-v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile

  QuitItTodayFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: qit-db-local
          DYNAMODB_ENDPOINT: http://qit-ddb-local:8000
          AWS_REGION: us-east-1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QitClickTable
      Events:
        QuitItToday:
          Type: Api
          Properties:
            Path: /quitItToday
            Method: post
      ImageConfig:
        Command:
          - quit-it-today.lambdaHandler
    Metadata:
      DockerTag: nodejs22.x-v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  HelloWorldFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt HelloWorldFunctionRole.Arn
  QuitItTodayApi:
    Description: 'API Gateway endpoint URL for Prod stage for QuitItToday function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quitItToday/'
  QuitItTodayFunction:
    Description: 'QuitItToday Lambda Function ARN'
    Value: !GetAtt QuitItTodayFunction.Arn
  QuitItTodayFunctionIamRole:
    Description: 'Implicit IAM Role created for QuitItToday function'
    Value: !GetAtt QuitItTodayFunctionRole.Arn
